### ISSUE TITLE
Vintage fixed crash bug notification -- Inkstitch Version Issue

### ISSUE THREAD

**Issue by tatarize** [EmbroidePy/pyembroidery#109]
@glangley1 your issue on inkscape/inkscape#887 is a bug in pyembroidery they have in their version. It was corrected here ages ago. Ask that they upgrade and correct their stuff. See issue #83 here. It was corrected.

@MangaValk
@kaalleen

**Comment by MangaValk** [comment]
https://github.com/inkstitch/inkstitch/pull/883
PR is already waiting on approval for a while. for now you can download the binaries in that pr.
