### ISSUE TITLE
How can I get dimensions of the design?

### ISSUE THREAD

**Issue by eduardobdamacena** [EmbroidePy/pyembroidery#122]
Someone can help me with a sample to get design dimensions (width and height)?

**Comment by samsal** [comment]
```python
bounds = [float(e) / 10.0 for e in pattern.bounds()]  # convert to mm.
width = bounds[2] - bounds[0]
height = bounds[3] - bounds[1]
```
from:
https://github.com/EmbroidePy/EmbroidePy/blob/a6614f90223ad351530c5a87525a573b237172bb/embroidepy/statisticsview.py#L47
