### ISSUE TITLE
+Xxx writer.

### ISSUE THREAD

**Issue by tatarize** [EmbroidePy/pyembroidery#41]
Adding in an Xxx writer. Apparently they are the only accepted format for Singer Quantum xl-6000 and kind of need exporting for my app. Also, was already a thing in libembroidery even though clearly a couple of the numbers are off. 

 "Singer Quantum XL-6000, .XXX file on Singer Compatible design card, Cable to computer connection"

@supertobi inkstitch/pyembroidery#69 I added .xxx writer but I likely need a check as to whether the resulting files sew. 

[butterfly.zip](https://github.com/EmbroidePy/pyembroidery/files/2537906/butterfly.zip)

Though there's clearly some other elements that need to be conveyed.

**Comment by supertobi** [comment]
I don't have the machine at them moment working, but the file looks good in "my editor":

![grafik](https://user-images.githubusercontent.com/653976/47911003-be0f4d00-de94-11e8-938a-8c4c6e859e2a.png)

**Comment by tatarize** [comment]
Yeah, that's the problem. I can run it through all my editors and it'll look fine. But that's no indication that they work on actual physical machines. Most editors skip around the file and ignore other things that the machines might find critical. Obviously if it fails on the editors it's going to fail on the machines but success on the editor doesn't imply success on the machine at all. There's plenty of elements that could be critical and defective for the machine that the editors don't care about.

**Comment by tatarize** [comment]
[butterfly.zip](https://github.com/EmbroidePy/pyembroidery/files/2550011/butterfly.zip)

Here's an updated copy. I should have properly stabilized the writer. That should be a pretty solid version, I got trims and double-checked the actual files and did the proper legwork. But, sewn on fabric is still the gold standard.
