### ISSUE TITLE
DST Open Bug.

### ISSUE THREAD

**Issue by tatarize** [EmbroidePy/pyembroidery#96]
Opening DST failed inkstitch/inkstitch#763
@sumsine  @kaalleen

This is the result of parsing the ascii header of dst files in ascii. And assuming they are all UTF8. Some programs will save the name in cyrillic or other alphabets, and the obsolete version of pyembroidery used there doesn't have that corrected. This was corrected here in October of 2019.

See #83 and the corrections in #84 and #88

**Comment by sumsine** [comment]
Thank you for your reply. 
I saved the mentioned .dst-file using inkstich "File->Save as->abc.dst". As long as I do not close the file I can work with it. But I can not open this file again. There are no letters in cyrillic or other alphabets. 
My work-around at the moment is to save what I did in .svg and transform it to .dst after that. So I can work with the .svg-file. 
Are there any other solutions? I am only a user, not a programmer.
Thank you

**Comment by tatarize** [comment]
The error you mentioned is specifically saying there is a non-utf8 character in the file. If send me a copy _tatarize at my gmail_ or zip it up and attach it here. I'll tell you where the weird character is. It's an older bug pyembroidery used to have. It's somehow trying to save something that isn't ascii in the header. You could likely open it up with a text editor and see them as well. The solution is quite likely to have the inkstitch people implement my same corrections here.

**Comment by sumsine** [comment]
Thank you. Here comes a file I created in inkscape.
[Fernseher.zip](https://github.com/EmbroidePy/pyembroidery/files/4941276/Fernseher.zip)

**Comment by LochanLoch** [comment]
No problem here with the DST file [Video 06 Visual Commands ](https://www.youtube.com/watch?v=RU0WzMYZ6ik&list=PLvlbfDmZyXG1ORmeqHdp4aP7J71e7icJP&index=11&t=0s) helped me a lot with the sometimes very funny filling :-)

**Comment by tatarize** [comment]
That file does not crash. Even in regular inkstitch. It's would if it had some non-utf character in it but the provided file cannot and does not crash.

I'd reinstall your copy of inkstitch. It might be weird consequence of internationalization somewhere.
