### ISSUE TITLE
Digitizer?

### ISSUE THREAD

**Issue by seghier** [EmbroidePy/pyembroidery#99]
Hello
thank you very much for this usefull module, i used it to convert and write txt file which is very useful
is it possible to add digitize feature in future? or this impossible?

**Comment by tatarize** [comment]
I've coded up that feature for MeerK40t (Laser Cutting software) at some point. It's certainly a kind of worthwhile feature to have. It isn't one that would ever be added to pyembroidery though. The specs on this project are intended to prevent feature bleed and bloating. As such no higher level commands like that would ever be added to this project. 

The sort of digitization fills are really something this project is intended to touch. This is laser focused on embroidery input and output, and some basic alterations of the embroidery to tweak it for input and output.

**Comment by seghier** [comment]
Thanks
i convert a dst file to txt than i tried to convert the same txt file to dst but nothing happened
is this conversion possible?

**Comment by tatarize** [comment]
Nope. The text doesn't have all the needed data, to be parsed. You could easily convert it to and from `csv` which is kinda related to the text file.

**Comment by seghier** [comment]
Thank you, csv looks better with more details and easily can extract some informations
i used your module with Rhino3d but **Rhino’s Python interpreter is based on IronPython, i can't import it directly**
i used another way , is it possible that your module will work with IronPython in future?

**Comment by JaredPhelps** [comment]
When I was looking into embroidery software to work with my .NET project I ran into the IronPython fork of this project here: https://github.com/fstwn/ironpyembroidery

It's about a year behind this repo but might be good enough for your purposes.

**Comment by seghier** [comment]
Thank you Jared , i will test it

**Comment by seghier** [comment]
Yes that's it , thank so much Jared
https://github.com/fstwn/pyembroideryGH

**Comment by tatarize** [comment]
Not much has changed in this Repo in a year or so. Just very minor updates and changes. It's been mostly done for a few years now.

**Comment by seghier** [comment]
Yes , but it is useful what i need is not very professional things
he already created plugins to work directly in Rhino

**Comment by seghier** [comment]
> I've coded up that feature for MeerK40t (Laser Cutting software) at some point. It's certainly a kind of worthwhile feature to have. It isn't one that would ever be added to pyembroidery though. The specs on this project are intended to prevent feature bleed and bloating. As such no higher level commands like that would ever be added to this project.
> 
> The sort of digitization fills are really something this project is intended to touch. This is laser focused on embroidery input and output, and some basic alterations of the embroidery to tweak it for input and output.

**Comment by seghier** [comment]
I've coded up that feature for MeerK40t
i download it but don't find the feature of Rastering?

**Comment by tatarize** [comment]
It's actually accessed in the console, if you select an svg object and you type 'embroider' it'll run the code. I think it's located in `OperationPreprocessor.py` for that functionality.

**Comment by tatarize** [comment]
https://youtu.be/t0cs2ppi4P0

**Comment by seghier** [comment]
Thank you , i try by importing svg file and use the command embroider ,but from the video it look need rasterization

**Comment by tatarize** [comment]
The important thing is that it can do the fill operation. It's not rastering. It's legit just converting the hollow image to one filled. I think there's also two suboptions in the embroidery command. I think they are angle and line distance or something like that. It's generally outside the scope of this project and I'm working on other things, so it won't turn into anything very useful anytime soon. It certainly works and can be adapted but I have a few other projects that certainly take priority.

**Comment by tatarize** [comment]
I specifically recoded and added this to a vpype plugin you'd find it: https://github.com/EmbroidePy/vpype-embroidery
